bin merge

diff --git a/bin/foamClearPolyMesh b/bin/foamClearPolyMesh
--- a/bin/foamClearPolyMesh
+++ b/bin/foamClearPolyMesh
@@ -27,20 +27,128 @@
 #     foamClearPolyMesh
 #
 # Description
-#     
+#    Remove the contents of the constant/polyMesh directory
+#    as per the Foam::polyMesh::removeFiles() method.
+#
 #------------------------------------------------------------------------------
+usage() {
+    while [ "$#" -ge 1 ]; do echo "$1" 1>&2; shift; done
+    cat <<USAGE 1>&2
 
-if [ -d constant/polyMesh ]; then
-    echo "there is constant/polyMesh";
-    cd constant/polyMesh
+usage: ${0##*/} [-case dir] [-region name]
 
-elif [ -d polyMesh ]; then
-    echo "there is polyMesh";
-    cd polyMesh
+    Remove the contents of the constant/polyMesh directory
+    as per the Foam::polyMesh::removeFiles() method.
+
+USAGE
+   exit 1
+}
+
+unset caseDir regionName
+
+# parse a single option
+while [ "$#" -gt 0 ]
+do
+    case "$1" in
+    -h | -help)
+        usage
+        ;;
+    -case)
+        [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
+        cd "$2" 2>/dev/null || usage "directory does not exist:  '$2'"
+        caseDir=$2
+        shift 2
+        ;;
+    -region)
+        [ "$#" -ge 2 ] || usage "'$1' option requires an argument"
+        regionName=$2
+        shift 2
+        ;;
+    *)
+        usage "unknown option/argument: '$*'"
+        ;;
+    esac
+done
+
+if [ -n "$regionName" ]
+then
+    meshDir=$regionName/polyMesh
 else
-    echo "in polyMesh directory";
+    meshDir=polyMesh
 fi
 
-rm -f pointFaces pointEdges pointCells faceEdges edges edgeFaces edgeCells cellEdges cellCells owner neighbour losort faceCentres faceAreas cellVolumes cellCentres
+# if -case was specified: insist upon 'constant/polyMesh'
+if [ -n "$caseDir" ]
+then
+    if [ -d constant/$meshDir ]
+    then
+        # use constant/polyMesh
+        meshDir=constant/$meshDir
+    else
+       echo "Error: no 'constant/$meshDir' in $caseDir" 1>&2
+       exit 1
+    fi
+else
+    if [ -d constant/$meshDir ]
+    then
+        # use constant/polyMesh
+        meshDir=constant/$meshDir
+    elif [ -d $meshDir ]
+    then
+        # likely already in constant/ - do not adjust anything
+        :
+    elif [ "${PWD##*/}" = polyMesh -a -z "$regionName" ]
+    then
+        # apparently already within polyMesh/
+        meshDir=.
+    else
+        echo "Error: no appropriate 'polyMesh/' directory found" 1>&2
+        exit 1
+    fi
+fi
+
+
+#
+# remove files (mesh itself, modifiers, snappyHexMesh ones) and subdirectories
+#
+echo "Clearing ${caseDir:-.}/$meshDir" 1>&2
+
+for i in \
+    points \
+    faces \
+    owner \
+    neighbour \
+    cells \
+    boundary \
+    pointZones \
+    faceZones \
+    cellZones \
+    meshModifiers \
+    parallelData \
+    sets \
+    cellLevel \
+    pointLevel \
+    refinementHistory \
+    surfaceIndex \
+    points.gz \
+    faces.gz \
+    owner.gz \
+    neighbour.gz \
+    cells.gz \
+    boundary.gz \
+    pointZones.gz \
+    faceZones.gz \
+    cellZones.gz \
+    meshModifiers.gz \
+    parallelData.gz \
+    sets.gz \
+    cellLevel.gz \
+    pointLevel.gz \
+    refinementHistory.gz \
+    surfaceIndex.gz \
+;
+do
+    rm -rf $meshDir/$i
+done
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamExec b/bin/foamExec
--- a/bin/foamExec
+++ b/bin/foamExec
@@ -40,10 +40,10 @@
 Script=${0##*/}
 
 usage() {
-   while [ "$#" -ge 1 ]; do echo "$1"; shift; done
-   cat<<USAGE
+    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
+    cat<<USAGE
 
-usage: $Script [OPTION] <application> ...
+usage: ${0##*/} [OPTION] <application> ...
 
 options:
   -v ver        specify OpenFOAM version
@@ -52,16 +52,17 @@ options:
 * run a particular OpenFOAM version of <application>
 
 USAGE
-   exit 1
+    exit 1
 }
+
 
 # This script should exist in <foamInstall>/OpenFOAM-<VERSION>/bin/
 # extract the <foamInstall> and <version> elements
 # using a function preserves the command args
 getDefaults() {
-   set -- $(echo $0 | sed -e 's@/OpenFOAM-\([^/]*\)/bin/[^/]*$@ \1@')
-   foamInstall=$1
-   version=$2
+    set -- $(echo $0 | sed -e 's@/OpenFOAM-\([^/]*\)/bin/[^/]*$@ \1@')
+    foamInstall=$1
+    version=$2
 }
 
 getDefaults
@@ -69,72 +70,60 @@ getDefaults
 # parse options
 while [ "$#" -gt 0 ]
 do
-   case "$1" in
-   -h | -help)
-      usage
-      ;;
-   -v)
-      shift
-      version=$1
-      shift
-      ;;
-   --)
-      shift
-      break
-      ;;
-   -*)
-      usage "invalid option '$1'"
-      ;;
-   *)
-      break
-      ;;
-   esac
+    case "$1" in
+    -h | -help)
+        usage
+        ;;
+    -v)
+        shift
+        version=$1
+        shift
+        ;;
+    --)
+        shift
+        break
+        ;;
+    -*)
+        usage "invalid option '$1'"
+        ;;
+    *)
+        break
+        ;;
+    esac
 done
 
-if [ "$#" -lt 1 ]; then
-   usage "no application specified"
+if [ "$#" -lt 1 ]
+then
+    usage "no application specified"
 fi
 
 unset foamDotFile
 
 # Check user-specific OpenFOAM bashrc file
-for subDir in \
-   $HOME/.OpenFOAM-$version \
-   $HOME/.OpenFOAM/$version \
-;
-do
-   foamDotFile="$subDir/bashrc"
-   if [ -f $foamDotFile ]; then
-      . $foamDotFile
-      foamDotFile=okay
-      break
-   fi
-done
-
-# Use the FOAM_INST_DIR variable for locating the installed version
-if [ "$foamDotFile" != okay ]
+foamDotFile="$HOME/.OpenFOAM/$version/bashrc"
+if [ -f $foamDotFile ]
 then
-   for FOAM_INST_DIR in $foamInstall $WM_PROJECT_INST_DIR
-   do
-      for subDir in \
-         OpenFOAM-$version/etc \
-         OpenFOAM-$version/.OpenFOAM-$version \
-      ;
-      do
-        foamDotFile="$FOAM_INST_DIR/$subDir/bashrc"
-        if [ -f $foamDotFile ]; then
-           . $foamDotFile
-           foamDotFile=okay
-           break 2
+    . $foamDotFile
+    foamDotFile=okay
+else
+    # Use the FOAM_INST_DIR variable for locating the installed version
+    for FOAM_INST_DIR in $foamInstall $WM_PROJECT_INST_DIR
+    do
+        foamDotFile="$FOAM_INST_DIR/OpenFOAM-$version/etc/bashrc"
+        if [ -f $foamDotFile ]
+        then
+            . $foamDotFile
+            foamDotFile=okay
+            break
         fi
-     done
-   done
+    done
 fi
 
-if [ "$foamDotFile" != okay ];
+
+if [ "$foamDotFile" != okay ]
 then
-   echo "Error : bashrc file could not be found for OpenFOAM-$version" 1>&2
-   exit 1
+    echo "Error : bashrc file could not be found for OpenFOAM-$version" 1>&2
+    exit 1
 fi
 
 # Pass on the rest of the arguments
diff --git a/bin/foamPack b/bin/foamPack
--- a/bin/foamPack
+++ b/bin/foamPack
@@ -38,19 +38,20 @@ packFile=${packDir}_${timeStamp}.tgz
 
 if [ ! -d $packDir ]
 then
-   echo "Error: directory $packDir does not exist"
-   exit 1
+    echo "Error: directory $packDir does not exist" 1>&2
+    exit 1
 fi
 
 # add optional output directory
-if [ -d "$1" ]; then
-   packFile="$1/$packFile"
+if [ -d "$1" ]
+then
+    packFile="$1/$packFile"
 fi
 
 if [ -f $packFile ]
 then
-   echo "Error: $packFile already exists"
-   exit 1
+    echo "Error: $packFile already exists" 1>&2
+    exit 1
 fi
 
 # Create time stamp file
@@ -88,8 +89,10 @@ find -H $packDir               \
  -e "\@$packDir/.git/@d"       \
  -e "\@.svn/@d"                  \
  -e "\@$packDir/lib/@d"        \
- -e '\@applications/bin/@d'       \
- -e '\@/t/@d'                     \
+ -e '\@/\.git/@d'              \
+ -e '\@applications/bin/@d'    \
+ -e '\@wmake/bin/@d'           \
+ -e '\@/t/@d'                  \
  -e '\@Make[.A-Za-z]*/[^/]*/@d'   \
  -e '\@doc/[Dd]oxygen/html@d'     \
  -e '\@doc/[Dd]oxygen/latex@d'    \
@@ -100,12 +103,12 @@ find -H $packDir               \
 
 tar czpf $packFile --files-from $tmpFile
 
-if [ $? = 0 ]
+if [ $? -eq 0 ]
 then
-   echo "Finished packing and compressing $packDir into file $packFile"
+    echo "Finished packing and compressing $packDir into file $packFile"
 else
-   echo "Error: failure packing $packDir into file $packFile"
-   rm -f $packFile 2>/dev/null
+    echo "Error: failure packing $packDir into file $packFile" 1>&2
+    rm -f $packFile 2>/dev/null
 fi
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamPackBin b/bin/foamPackBin
--- a/bin/foamPackBin
+++ b/bin/foamPackBin
@@ -30,113 +30,71 @@
 #     Packs and compresses binary version of OpenFOAM for release
 #
 #------------------------------------------------------------------------------
-tmpDir=${TMPDIR:-/tmp}/foamPackDir.$$
 
-#
-# FUNCTIONS
-#
-printUsage () {
-cat <<EOF
-   Usage : ${0##*/} [-l] <arch> [outputDir]"
-EOF
-}
-
-timeStamp=$(date +%Y-%m-%d)
-packDir=$WM_PROJECT-$WM_PROJECT_VERSION
-packFile=${packDir}.${arch}_${timeStamp}.tgz
-
-#
-# OPTIONS
-#
-OPTS=`getopt hl $*`
-if [ $? -ne 0 ] ; then
-    echo "Aborting due to invalid option"
-    printUsage
+if [ $# -eq 0 ]
+then
+    echo "Error: architecture type expected, exiting"
+    echo
+    echo "Usage : ${0##*/} <arch> [outputDir]"
+    echo
     exit 1
-fi
-
-eval set -- '$OPTS'
-while [ "$1" != "--" ]; do
-    case $1 in
-        -l) LZM=1;;
-        -h) printUsage; exit 1;;
-    esac
-    shift
-done
-shift
-
-if [ $# = 0 ]; then
-   printUsage;
-   exit 1
 fi
 arch=$1
 
-if [ $LZM ]; then
-   packFile=${packDir}.${arch}_${timeStamp}.lzm
-else
-   packFile=${packDir}.${arch}_${timeStamp}.tgz
-fi
+# base arch (w/o precision, optimization, etc)
+baseArch=$(echo "$arch" | sed -e 's@[DS]P.*$@@')
+
+timeStamp=$(date +%Y-%m-%d)
+packDir=$WM_PROJECT-$WM_PROJECT_VERSION
+packFile=${packDir}.${arch}_${timeStamp}.gtgz
 
 # add optional output directory
-if [ -d "$2" ]; then
-   packFile="$2/$packFile"
+if [ -d "$2" ]
+then
+    packFile="$2/$packFile"
 fi
 
-if [ -f $packFile ]; then
-   echo "Error: $packFile already exists"
-   exit 1
+if [ -f $packFile ]
+then
+    echo "Error: $packFile already exists"
+    exit 1
 fi
 
 # check for essential directories
 for dir in $packDir $packDir/lib/$arch $packDir/applications/bin/$arch
 do
-   if [ ! -d $dir ]; then
-      echo "Error: directory $dir does not exist"
-      exit 1
-   fi
+    if [ ! -d $dir ]
+    then
+        echo "Error: directory $dir does not exist"
+        exit 1
+    fi
 done
 
 # get list of directories
 dirList=$(
-   for dir in \
-      $packDir/lib/$arch \
-      $packDir/applications/bin/$arch \
-      $packDir/wmake/rules \
-      ;
-   do
-      [ -d $dir ] && echo $dir
-   done
+    for dir in \
+        $packDir/lib/$arch \
+        $packDir/applications/bin/$arch \
+        $packDir/wmake/rules \
+        $packDir/wmake/bin/$baseArch \
+        ;
+    do
+        [ -d $dir ] && echo $dir
+    done
 )
 
 echo
-echo "Packing $arch port of $packDir into $packFile"
+echo "Packing $arch ($baseArch) port of $packDir into $packFile"
 echo
 
-if [ $LZM ]; then
+tar czpf $packFile $dirList
 
-   # Clean up on termination and on Ctrl-C
-   trap 'rm -rf $tmpDir 2>/dev/null; exit 0' EXIT TERM INT
-
-   mkdir $tmpDir $tmpDir/OpenFOAM
-   cp -arl --parents $dirList $tmpDir/OpenFOAM
-   find $tmpDir -name .svn | xargs rm -rf
-
-   chmod -R a+rX $tmpDir/OpenFOAM
-   foamDir2lzm $tmpDir $packFile
-   echo; echo
-
-else
-
-   tar --exclude-vcs czpf $packFile $dirList
-
-fi
-
-if [ $? = 0 ]
+if [ $? -eq 0 ]
 then
-   echo "Finished packing and compressing file $packFile"
+    echo "Finished packing and compressing file $packFile"
 else
-   echo "Error: failure packing $packFile"
-   rm -f $packFile 2>/dev/null
+    echo "Error: failure packing $packFile"
+    rm -f $packFile 2>/dev/null
 fi
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamPackBinAll b/bin/foamPackBinAll
--- a/bin/foamPackBinAll
+++ b/bin/foamPackBinAll
@@ -27,20 +27,21 @@
 #     foamPackBinAll [outputDir]
 #
 # Description
-#     Packs and compresses all binary version of foam for release
+#     Packs and compresses all binary versions of foam for release
 #
 #------------------------------------------------------------------------------
 packDir=$WM_PROJECT-$WM_PROJECT_VERSION
 
 if [ ! -d $packDir ]
 then
-   echo "Error: directory $packDir does not exist"
-   exit 1
+    echo "Error: directory $packDir does not exist"
+    exit 1
 fi
 
+# obtain arch types from lib/
 for bin in $packDir/lib/*
 do
-   foamPackBin ${bin##*/} $@
+    foamPackBin ${bin##*/} $@
 done
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamPackGeneral b/bin/foamPackGeneral
--- a/bin/foamPackGeneral
+++ b/bin/foamPackGeneral
@@ -31,50 +31,26 @@
 #
 #------------------------------------------------------------------------------
 
-#
-# FUNCTIONS
-#
-printUsage () {
-cat <<EOF
-   Usage : ${0##*/} " [-l] [outputDir]
-
-   Packs and compresses the OpenFOAM directory for release
-EOF
-}
-
 timeStamp=$(date +%Y-%m-%d)
 packDir=$WM_PROJECT-$WM_PROJECT_VERSION
 packFile=${packDir}.General_${timeStamp}.tgz
-LZMOPT=""
 
-#
-# OPTIONS
-#
-OPTS=`getopt hl $*`
-if [ $? -ne 0 ] ; then
-    echo "Error: Aborting due to invalid option"
-    printUsage;
+if [ ! -d $packDir ]
+then
+    echo "Error: directory $packDir does not exist"
     exit 1
 fi
 
-eval set -- '$OPTS'
-while [ "$1" != "--" ]; do
-    case $1 in
-        -l) LZMOPT="-l"; packFile=${packDir}.General_${timeStamp}.lzm;;
-        -h) printUsage; exit 1;;
-    esac
-    shift
-done
-shift
-
 # add optional output directory
-if [ -d "$1" ]; then
-   packFile="$1/$packFile"
+if [ -d "$1" ]
+then
+    packFile="$1/$packFile"
 fi
 
-if [ -f $packFile ]; then
-   echo "Error: $packFile already exists"
-   exit 1
+if [ -f $packFile ]
+then
+    echo "Error: $packFile already exists"
+    exit 1
 fi
 
 # Create time stamp file
@@ -86,9 +62,9 @@ echo $timeStamp 2>/dev/null > $packDir/.timeStamp
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
 echo
-echo "Packing $packDir into $packFile"
+echo "Packing $packDir source files into $packFile"
 echo
 
-foamPackSource $LZMOPT $packDir $packFile
+foamPackSource $packDir $packFile
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamPackSource b/bin/foamPackSource
--- a/bin/foamPackSource
+++ b/bin/foamPackSource
@@ -32,56 +32,31 @@
 #
 #------------------------------------------------------------------------------
 tmpFile=${TMPDIR:-/tmp}/foamPackFiles.$$
-tmpDir=${TMPDIR:-/tmp}/foamPackDir.$$
 
-#
-# FUNCTIONS
-#
-printUsage () {
-cat <<EOF
-   Usage : ${0##*/} directory tarFile
-
-   Packs all .C and .H files and Make/options and Make/files into <tarFile>
-EOF
-}
-
-#
-# OPTIONS
-#
-OPTS=`getopt hl $*`
-if [ $? -ne 0 ] ; then
-    echo "Error: Aborting due to invalid option"
-    printUsage;
+if [ $# -ne 2 ]
+then
+    echo "Usage : ${0##*/} directory tarFile"
+    echo ""
+    echo "Packs all .C and .H files and Make/options and Make/files into"
+    echo "<tarFile>"
+    echo ""
     exit 1
-fi
-
-eval set -- '$OPTS'
-while [ "$1" != "--" ]; do
-    case $1 in
-        -l) LZM=1;;
-        -h) printUsage; exit 1;;
-    esac
-    shift
-done
-shift
-
-if [ $# -ne 2 ]; then
-   printUsage;
-   exit 1
 fi
 
 # canonical form (no double and no trailing dashes)
 packDir=$(echo "$1" | sed -e 's@//*@/@g' -e 's@/$@@')
 packFile=$2
 
-if [ ! -d $packDir ]; then
-   echo "Error: directory $packDir does not exist"
-   exit 1
+if [ ! -d $packDir ]
+then
+    echo "Error: directory $packDir does not exist"
+    exit 1
 fi
 
-if [ -f $packFile ]; then
-   echo "Error: $packFile already exists"
-   exit 1
+if [ -f $packFile ]
+then
+    echo "Error: $packFile already exists"
+    exit 1
 fi
 
 # Clean up on termination and on Ctrl-C
@@ -107,36 +82,29 @@ find -H $packDir               \
  -e "\@$packDir/.git/@d"       \
  -e "\@.svn/@d"                \
  -e "\@$packDir/lib/@d"        \
+ -e '\@/\.git/@d'              \
+ -e '\@/\.tags/@d'             \
  -e '\@applications/bin/@d'    \
+ -e '\@wmake/bin/@d'           \
  -e '\@/t/@d'                  \
  -e '\@/Make[.A-Za-z]*/[^/]*/@d'\
  -e '\@/platforms/@d'          \
+ -e '\@libccmio.*/@d'          \
  -e '\@/.svn/@d'               \
  > $tmpFile
 
-if [ $LZM ]; then
 
-   # Clean up on termination and on Ctrl-C
-   trap 'rm -f $tmpFile 2>/dev/null; rm -rf $tmpDir 2>/dev/null; exit 0' EXIT TERM INT
+# provide some feedback
+wc $tmpFile | awk '{print "Packing",$1,"files - this could take some time ..."}'
 
-   mkdir $tmpDir $tmpDir/OpenFOAM
-   xargs -i -a $tmpFile cp -al --parents {} $tmpDir/OpenFOAM
+tar czpf $packFile --files-from $tmpFile
 
-   chmod -R a+rX $tmpDir/OpenFOAM
-   foamDir2lzm $tmpDir $packFile
-   echo; echo
-
-else
-
-   tar czpf $packFile --files-from $tmpFile
-
-fi
-
-if [ $? = 0 ]; then
+if [ $? -eq 0 ]
+then
    echo "Finished packing and compressing $packDir into file $packFile"
 else
-   echo "Error: failure packing $packDir into file $packFile"
-   rm -f $packFile 2>/dev/null
+    echo "Error: failure packing $packDir into file $packFile"
+    rm -f $packFile 2>/dev/null
 fi
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamPackThirdPartyBin b/bin/foamPackThirdPartyBin
--- a/bin/foamPackThirdPartyBin
+++ b/bin/foamPackThirdPartyBin
@@ -30,72 +30,44 @@
 #     Packs and compresses binary version of OpenFOAM ThirdParty for release
 #
 #------------------------------------------------------------------------------
-tmpDir=${TMPDIR:-/tmp}/foamPackDir.$$
 
-#
-# FUNCTIONS
-#
-printUsage () {
-cat <<EOF
-   Usage : ${0##*/} [-l] <archOptions> [outputDir]"
-EOF
-}
-
-timeStamp=$(date +%Y-%m-%d)
-packDir=$WM_PROJECT-$WM_PROJECT_VERSION
-packFile=${packDir}.${arch}_${timeStamp}.tgz
-
-#
-# OPTIONS
-#
-OPTS=`getopt hl $*`
-if [ $? -ne 0 ] ; then
-    echo "Aborting due to invalid option"
-    printUsage
+if [ $# -eq 0 ]
+then
+    echo "Error: archOptions type expected, exiting"
+    echo
+    echo "Usage : ${0##*/} <archOptions> [outputDir]"
+    echo
     exit 1
 fi
-
-eval set -- '$OPTS'
-while [ "$1" != "--" ]; do
-    case $1 in
-        -l) LZM=1;;
-        -h) printUsage; exit 1;;
-    esac
-    shift
-done
-shift
-
-if [ $# = 0 ]; then
-   printUsage;
-   exit 1
-fi
 archOptions=$1
-arch=${archOptions%%G*}
-arch3264=$(echo "$arch" | sed 's@64@-64@')
+arch=${archOptions%%G*}  # TODO: works for Gcc only
+arch3264=$(echo "$arch" | sed -e 's@64@-64@')
 
 echo "archOptions=$archOptions"
 echo "arch=$arch"
 echo "arch3264=$arch3264"
 
 timeStamp=$(date +%Y-%m-%d)
-packDir=ThirdParty
+packDir=${WM_THIRD_PARTY_DIR:-ThirdParty}
+packDir=${packDir##*/}
+packFile=${packDir}.${archOptions}_${timeStamp}.tgz
 
-if [ $LZM ]; then
-   packFile=${packDir}.${arch}_${timeStamp}.lzm
-else
-   packFile=${packDir}.${arch}_${timeStamp}.tgz
+if [ ! -d $packDir ]
+then
+    echo "Error: directory $packDir does not exist"
+    exit 1
 fi
 
 # add optional output directory
 if [ -d "$2" ]
 then
-   packFile="$2/$packFile"
+    packFile="$2/$packFile"
 fi
 
 if [ -f $packFile ]
 then
-   echo "Error: $packFile already exists"
-   exit 1
+    echo "Error: $packFile already exists"
+    exit 1
 fi
 
 # get list of directories
@@ -104,28 +76,14 @@ echo
 echo "Packing $archOptions port of $packDir into $packFile"
 echo
 
-if [ $LZM ]; then
+tar czpf $packFile $dirList
 
-   # Clean up on termination and on Ctrl-C
-   trap 'rm -rf $tmpDir 2>/dev/null; exit 0' EXIT TERM INT
-
-   mkdir $tmpDir $tmpDir/OpenFOAM
-   cp -arl --parents $dirList $tmpDir/OpenFOAM
-   foamDir2lzm $tmpDir $packFile
-   echo; echo
-
-else
-
-   tar czpf $packFile $dirList
-
-fi
-
-if [ $? = 0 ]
+if [ $? -eq 0 ]
 then
-   echo "Finished packing and compressing file $packFile"
+    echo "Finished packing and compressing file $packFile"
 else
-   echo "Error: failure packing $packFile"
-   rm -f $packFile 2>/dev/null
+    echo "Error: failure packing $packFile"
+    rm -f $packFile 2>/dev/null
 fi
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamUpdateCaseFileHeader b/bin/foamUpdateCaseFileHeader
--- a/bin/foamUpdateCaseFileHeader
+++ b/bin/foamUpdateCaseFileHeader
@@ -33,85 +33,111 @@
 #     Also removes consecutive blank lines from file.
 #
 #------------------------------------------------------------------------------
+foamVersion=$WM_PROJECT_VERSION
 
-#
-# FUNCTIONS
-#
-printUsage () {
-cat <<EOF
-Usage: $0 <file>
-    Updates the header of application files
-    By default, writes current version in the header
-    Alternatively version can be specified with -v option
-    Also removes consecutive blank lines from file
+usage() {
+    cat<<USAGE
 
-Options are:
--v "<version>" specifies the version to be written in the header
--h         help
-EOF
+Usage: ${0##*/} [OPTION] <file1> ... <fileN>
+
+options:
+  -v VER  specifies the version to be written in the header
+  -h      help
+
+  Updates the header of application files and removes consecutive blank lines.
+  By default, writes current OpenFOAM version in the header.
+  An alternative version can be specified with the -v option.
+
+USAGE
+    exit 1
 }
 
-printOpenFOAMheader () {
-cat<<EOF
+
+printHeader() {
+    cat<<HEADER
 /*--------------------------------*- C++ -*----------------------------------*\\
 | =========                 |                                                 |
 | \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
-|  \\\\    /   O peration     | Version:  ${1}                                   |
-|   \\\\  /    A nd           | Web:      http://www.OpenFOAM.org               |
+|  \\\\    /   O peration     | Version:  ${foamVersion}  |
+|   \\\\  /    A nd           | Web:      www.OpenFOAM.org                      |
 |    \\\\/     M anipulation  |                                                 |
 \\*---------------------------------------------------------------------------*/
 FoamFile
 {
     version     2.0;
-    format      ${2};
-    class       ${3};
-    object      ${4};
+    format      ${1};
+    class       ${2};
+    object      ${3};
 }
-EOF
-}
-
-FoamFileAttribute () {
-    grep $1 $2 | tr -s " " | cut -d" " -f3 | cut -d\; -f1
+HEADER
 }
 
-VERSION=$WM_PROJECT_VERSION
+
+#
+# extract attribute '$1' from file '$2'
+#
+FoamFileAttribute() {
+    sed -n -e 's/[ ;]*$//' -e "s/^ *$1 *//p" $2
+}
+
+
 #
 # OPTIONS
 #
-OPTS=`getopt hv: $*`
-if [ $? -ne 0 ] ; then
+opts=$(getopt hv: $*)
+if [ $? -ne 0 ]
+then
     echo "Aborting due to invalid option"
-    printUsage
-    exit 1
+    usage
 fi
-eval set -- '$OPTS'
-while [ "$1" != "--" ]; do
+eval set -- '$opts'
+while [ "$1" != "--" ]
+do
     case $1 in
-        -v) VERSION=$2; shift;;
-        -h) printUsage; exit 1;;
+    -v)
+        foamVersion=$2
+        shift
+        ;;
+    -h)
+        usage
+        ;;
     esac
     shift
 done
 shift
 
+[ $# -ge 1 ] || usage
+
+
+# constant width for version
+foamVersion=$(printf %-36s $foamVersion)
+
 #
 # MAIN
 #
-CASE_FILE=$1
-if [ "`grep FoamFile $CASE_FILE`" ] ; then
-    echo "Updating case file:" $CASE_FILE
-    sed -n '/FoamFile/,/}/p' $CASE_FILE > FoamFile
-    CLASS=`FoamFileAttribute class FoamFile`
-    OBJECT=`FoamFileAttribute object FoamFile`
-    FORMAT=`FoamFileAttribute format FoamFile`
-    printOpenFOAMheader $VERSION $FORMAT $CLASS $OBJECT > temp
-    sed '1,/}/d' $CASE_FILE | sed '/./,/^$/!d' >> temp
-    mv temp $1
-    rm FoamFile
-else
-    echo "The following file does not appear to be a case file:"
-    echo "    " $CASE_FILE
-fi
+unset NOTE
 
+for caseFile
+do
+    if grep FoamFile $caseFile >/dev/null 2>&1
+    then
+        echo "Updating case file: $caseFile"
+        sed -n '/FoamFile/,/}/p' $caseFile > FoamFile.tmp
+
+        FORMAT=$(FoamFileAttribute format FoamFile.tmp)
+        CLASS=$(FoamFileAttribute  class  FoamFile.tmp)
+        OBJECT=$(FoamFileAttribute object FoamFile.tmp)
+        # extract NOTE?
+
+        printHeader $FORMAT $CLASS $OBJECT $NOTE > FoamFile.tmp
+        sed '1,/}/d' $caseFile | sed '/./,/^$/!d' >> FoamFile.tmp
+
+        # use cat to avoid removing/replace soft-links
+        [ -s FoamFile.tmp ] && cat FoamFile.tmp >| $caseFile
+        rm -f FoamFile.tmp 2>/dev/null
+    else
+        echo " Invalid case file: $caseFile" 1>&2
+    fi
+done
 
 #------------------------------------------------------------------------------
diff --git a/bin/foamUpgradeTurbulenceProperties b/bin/foamUpgradeTurbulenceProperties
--- a/bin/foamUpgradeTurbulenceProperties
+++ b/bin/foamUpgradeTurbulenceProperties
@@ -30,59 +30,69 @@
 #     Upgrade the turbulenceProperties dictionary to the new format employed
 #     in OpenFOAM version 1.5-dev
 #     - RAS turbulence models now defined by the RASProperties dictionary,
-#       and RASModel keyword, and
+#       and RASModel keyword.
 #     - LES turbulence models now defined by the LESProperties dictionary,
 #       and LESModel keyword.
 #
 #------------------------------------------------------------------------------
 
-printUsage()
-{
-    echo "Usage: `basename $0` <turbulenceProperties>"
-    echo "    Where <turbulenceProperties> is the full path to the"
-    echo "    turbulenceProperties dictionary"
+usage() {
+    cat<<USAGE
+
+usage: ${0##*/} <turbulenceProperties>
+
+  Where <turbulenceProperties> is the full path to the
+  turbulenceProperties dictionary
+
+  Note: can upgrade several files at once
+
+USAGE
+   exit 1
 }
 
+#
+# $1: turbulence model
+# $2: new properties type
+# $3: original dictionary
+#
 convertDict()
 {
-    echo "    Identified $1 turbulence model"
+    echo "Identified $1 turbulence model in '$3'"
+    outputPath=`dirname $3`
 
-    sed -e "s/turbulenceProperties/$1Properties/" \
-        -e "s/$2/$1Model/" \
-        -e "s/[a-zA-Z0-9]* [ ]*\[[0-9 ]*\]//" \
-        $3 > "$outputPath/$1Properties"
+    if [ -e "$outputPath/$1Properties" ]
+    then
+        echo "Error: file already exists $outputPath/$1Properties'" 1>&2
+    else
+        sed -e "s/turbulenceProperties/$1Properties/" \
+            -e "s/$2/$1Model/" \
+            -e "s/[a-zA-Z0-9]* [ ]*\[[0-9 ]*\]//" \
+            $3 > "$outputPath/$1Properties"
 
-    echo "    written $1Properties to $outputPath/"
+        echo "    wrote $outputPath/$1Properties"
+    fi
 }
 
-outputPath=`dirname $1`
+[ $# -ge 1 ] || usage
 
-if [ $# -ne 1 ]; then
-    printUsage
-    exit 1
-elif [ ! -e $1 ]; then
-    echo "    Error: file $1 does not exist"
-    echo ""
-    printUsage
-    exit 1
-fi
-
-# Identify type of turbulence model
-RAS=`grep turbulenceModel $1`
-LES=`grep LESmodel $1`
-
-if [ -n "$RAS" ]; then
-    convertDict "RAS" "turbulenceModel" $1
-elif [ -n "$LES" ]; then
-    convertDict "LES" "LESmodel" $1
-else
-    echo "Unable to determine turbulence model type - nothing changed"
-    exit 1
-fi
-
-echo "done."
-
-exit 0
-
+for turbDict
+do
+    # Identify type of turbulence model and convert
+    if [ -f $turbDict ]
+    then
+        if grep turbulenceModel $turbDict >/dev/null 2>&1
+        then
+            convertDict RAS turbulenceModel $turbDict
+        elif grep LESmodel $turbDict >/dev/null 2>&1
+        then
+            convertDict LES LESmodel $turbDict
+        else
+            echo "Unable to determine turbulence model type in '$turbDict'" 1>&2
+            echo "    - nothing changed" 1>&2
+        fi
+    else
+        echo "Error: file '$turbDict' does not exist" 1>&2
+    fi
+done
 
 #------------------------------------------------------------------------------
