Porting, compilation

diff --git a/Allwmake b/Allwmake
--- a/Allwmake
+++ b/Allwmake
@@ -1,19 +1,27 @@
 #!/bin/sh
-set -x
+cd ${0%/*} || exit 1    # run from this directory
 
-# run from this directory only
-cd ${0%/*} || exit 1
+if [ "$PWD" != "$WM_PROJECT_DIR" ]
+then
+    echo "Error: Current directory is not \$WM_PROJECT_DIR"
+    echo "    The environment variable are not consistent with the installation."
+    echo "    Check the OpenFOAM entries in your dot-files and source them."
+    exit 1
+fi
 
 # wmake is required for subsequent targets
-(cd wmake/src && make)
+( cd wmake/src && make )
 
-(cd $WM_THIRD_PARTY_DIR && ./Allwmake)
+# build ThirdParty sources
+( cd $WM_THIRD_PARTY_DIR && ./Allwmake )
 
-(cd src && ./Allwmake)
-
-(cd applications && ./Allwmake)
+# build OpenFOAM libraries and applications
+src/Allwmake
+applications/Allwmake
 
 if [ "$1" = doc ]
 then
-   (cd doc && ./Allwmake)
+    doc/Allwmake
 fi
+
+# ----------------------------------------------------------------- end-of-file
diff --git a/src/Allwmake b/src/Allwmake
--- a/src/Allwmake
+++ b/src/Allwmake
@@ -1,4 +1,14 @@
 #!/bin/sh
+cd ${0%/*} || exit 1    # run from this directory
+
+if [ "$PWD" != "$WM_PROJECT_DIR/src" ]
+then
+    echo "Error: Current directory in not \$WM_PROJECT_DIR/src"
+    echo "    The environment variable are not consistent with the installation."
+    echo "    Check the OpenFOAM entries in your dot-files and source them."
+    exit 1
+fi
+
 set -x
 
 # update OpenFOAM version strings if required
@@ -28,10 +38,10 @@ wmake libso finiteArea
 wmake libso lduSolvers
 wmake libso dynamicMesh
 
-( cd tetDecompositionFiniteElement ; ./Allwmake )
+(cd tetDecompositionFiniteElement ; Allwmake)
 
 wmake libso fvMotionSolver
-( cd  tetDecompositionMotionSolver; ./Allwmake )
+(cd tetDecompositionMotionSolver ; Allwmake)
 
 wmake libso coupledMatrix
 wmake libso sampling
@@ -43,14 +53,19 @@ wmake libso engine
 wmake libso ODE
 wmake libso randomProcesses
 
-( cd thermophysicalModels && ./Allwmake )
-( cd transportModels && ./Allwmake )
-( cd turbulenceModels && ./Allwmake )
-( cd lagrangian && ./Allwmake )
-( cd postProcessing && ./Allwmake )
-( cd conversion && ./Allwmake )
+thermophysicalModels/Allwmake
+transportModels/Allwmake
+turbulenceModels/Allwmake
+lagrangian/Allwmake
+postProcessing/Allwmake
+conversion/Allwmake
 
 wmake libso autoMesh
 wmake libso errorEstimation
+
+fvAgglomerationMethods/Allwmake
+
+wmake libso fvMotionSolver
+wmake libso engine
 
 # ----------------------------------------------------------------- end-of-file
