New PyFoam scripts for modifying GGI and mixingPlane interfaces definitions in the 'boundary' dictionary. Adjustement to the mixingPlane tutorials

diff --git a/tutorials/incompressible/icoFoam/mixingPlane/twoBlocksMixingPlane_dirZ_spanY/Allrun b/tutorials/incompressible/icoFoam/mixingPlane/twoBlocksMixingPlane_dirZ_spanY/Allrun
--- a/tutorials/incompressible/icoFoam/mixingPlane/twoBlocksMixingPlane_dirZ_spanY/Allrun
+++ b/tutorials/incompressible/icoFoam/mixingPlane/twoBlocksMixingPlane_dirZ_spanY/Allrun
@@ -10,13 +10,39 @@
 export caseName=`basename $PWD`
 
 #We stop this script when we encounter a problem
-trap "exit -1" ERR
+#trap "exit -1" ERR
 
 echo "$caseName: Running blockMesh"
 runApplicationAndReportOnError blockMesh
 
 echo "$caseName: Updating the boundary file"
-cp constant/polyMesh/boundary.preconfigured constant/polyMesh/boundary
+# Let's see if pyFoamChangeMixingPlaneBoundary.py is available
+command -v pyFoamChangeMixingPlaneBoundary.py >/dev/null
+if [ $? -eq 0 ];
+then
+    echo "Using pyFoamChangeMixingPlaneBoundary.py"
+    pyFoamChangeMixingPlaneBoundary.py . mixpLeftOut      \
+	--shadowPatch                    mixpRightIn      \
+	--assembly                       both             \
+	--orientation                    dirZ_spanY       \
+	--coordinateSystemType           coordinateSystem \
+	--coordinateSystemOrigin         "(0 0 0.005)"    \
+	--coordinateSystemE1             "(1 0 0)"        \
+	--coordinateSystemE3             "(0 0 1)"        
+
+    pyFoamChangeMixingPlaneBoundary.py . mixpRightIn      \
+	--shadowPatch                    mixpLeftOut      \
+	--assembly                       both             \
+	--orientation                    dirZ_spanY       \
+	--coordinateSystemType           coordinateSystem \
+	--coordinateSystemOrigin         "(0 0 0.005)"    \
+	--coordinateSystemE1             "(1 0 0)"        \
+	--coordinateSystemE3             "(0 0 1)"        
+else
+    echo "pyFoamChangeMixingPlaneBoundary.py is missing. Using the file constant/polyMesh/boundary.preconfigured"
+    cp constant/polyMesh/boundary.preconfigured constant/polyMesh/boundary
+fi
+
 
 echo "$caseName: Creating the starting time directory"
 cp -r 0_orig 0
diff --git a/tutorials/incompressible/simpleFoam/ERCOFTAC_ConicalDiffuser/Case1.1_GGI/Allrun b/tutorials/incompressible/simpleFoam/ERCOFTAC_ConicalDiffuser/Case1.1_GGI/Allrun
--- a/tutorials/incompressible/simpleFoam/ERCOFTAC_ConicalDiffuser/Case1.1_GGI/Allrun
+++ b/tutorials/incompressible/simpleFoam/ERCOFTAC_ConicalDiffuser/Case1.1_GGI/Allrun
@@ -10,7 +10,7 @@
 export caseName=`basename $PWD`
 
 #We stop this script when we encounter a problem
-trap "exit -1" ERR
+#trap "exit -1" ERR
 
 echo "$caseName: Creating the file blockMeshDict using m4"
 (cd constant/polyMesh; m4 -P blockMeshDict.m4 > blockMeshDict)
@@ -19,7 +19,25 @@ echo "$caseName: Running blockMesh"
 runApplicationAndReportOnError blockMesh
 
 echo "$caseName: Updating the boundary file"
-cp constant/polyMesh/boundary.preconfigured constant/polyMesh/boundary
+# Let's see if pyFoamChangeGGIBoundary.py is available
+command -v pyFoamChangeGGIBoundary.py >/dev/null
+if [ $? -eq 0 ];
+then
+    echo "Using pyFoamChangeGGIBoundary.py"
+    pyFoamChangeGGIBoundary.py . B_UPSTREAM     \
+        --shadowPatch            B_DOWNSTREAM   \
+        --zone                   B_UPSTREAMZone \
+	--bridgeOverlap          false
+
+    pyFoamChangeGGIBoundary.py . B_DOWNSTREAM     \
+        --shadowPatch            B_UPSTREAM       \
+        --zone                   B_DOWNSTREAMZone \
+	--bridgeOverlap          false
+
+else
+    echo "pyFoamChangeGGIBoundary.py is missing. Using the file constant/polyMesh/boundary.preconfigured"
+    cp constant/polyMesh/boundary.preconfigured constant/polyMesh/boundary
+fi
 
 echo "$caseName: Creating the starting time directory"
 cp -r 0_orig 0
diff --git a/tutorials/incompressible/simpleFoam/ERCOFTAC_ConicalDiffuser/Case1.1_GGI_sector_90deg/Allrun b/tutorials/incompressible/simpleFoam/ERCOFTAC_ConicalDiffuser/Case1.1_GGI_sector_90deg/Allrun
--- a/tutorials/incompressible/simpleFoam/ERCOFTAC_ConicalDiffuser/Case1.1_GGI_sector_90deg/Allrun
+++ b/tutorials/incompressible/simpleFoam/ERCOFTAC_ConicalDiffuser/Case1.1_GGI_sector_90deg/Allrun
@@ -10,7 +10,7 @@
 export caseName=`basename $PWD`
 
 #We stop this script when we encounter a problem
-trap "exit -1" ERR
+#trap "exit -1" ERR
 
 echo "$caseName: Creating the file blockMeshDict using m4"
 (cd constant/polyMesh; m4 -P blockMeshDict.m4 > blockMeshDict)
@@ -19,7 +19,85 @@ echo "$caseName: Running blockMesh"
 runApplicationAndReportOnError blockMesh
 
 echo "$caseName: Updating the boundary file"
-cp constant/polyMesh/boundary.preconfigured constant/polyMesh/boundary
+# Let's see if pyFoamChangeGGIBoundary.py is available
+command -v pyFoamChangeGGIBoundary.py >/dev/null
+if [ $? -eq 0 ];
+then
+    echo "Using pyFoamChangeGGIBoundary.py"
+    pyFoamChangeGGIBoundary.py . B_UPSTREAM       \
+        --shadowPatch            B_DOWNSTREAM     \
+        --zone                   B_UPSTREAMZone   \
+	--bridgeOverlap          false
+
+    pyFoamChangeGGIBoundary.py . B_DOWNSTREAM     \
+        --shadowPatch            B_UPSTREAM       \
+        --zone                   B_DOWNSTREAMZone \
+	--bridgeOverlap          false
+
+    pyFoamChangeGGIBoundary.py . sideWallA_BB_cyclic1    \
+        --shadowPatch            sideWallA_BB_cyclic2    \
+        --rotationAxis           "(0 0 1)"               \
+        --rotationAngle          90                      \
+        --zone                   sideWallA_BB_cyclic1Zone
+
+    pyFoamChangeGGIBoundary.py . sideWallA_BB_cyclic2    \
+        --shadowPatch            sideWallA_BB_cyclic1    \
+        --rotationAxis           "(0 0 1)"               \
+        --rotationAngle          -90                     \
+        --zone                   sideWallA_BB_cyclic2Zone
+
+    pyFoamChangeGGIBoundary.py . sideWallB_C_cyclic1    \
+        --shadowPatch            sideWallB_C_cyclic2    \
+        --rotationAxis           "(0 0 1)"              \
+        --rotationAngle          90                     \
+        --zone                   sideWallB_C_cyclic1Zone
+
+    pyFoamChangeGGIBoundary.py . sideWallB_C_cyclic2    \
+        --shadowPatch            sideWallB_C_cyclic1    \
+        --rotationAxis           "(0 0 1)"              \
+        --rotationAngle          -90                    \
+        --zone                   sideWallB_C_cyclic2Zone
+
+    pyFoamChangeGGIBoundary.py . sideWallC_D_cyclic1    \
+        --shadowPatch            sideWallC_D_cyclic2    \
+        --rotationAxis           "(0 0 1)"              \
+        --rotationAngle          90                     \
+        --zone                   sideWallC_D_cyclic1Zone
+
+    pyFoamChangeGGIBoundary.py . sideWallC_D_cyclic2    \
+        --shadowPatch            sideWallC_D_cyclic1    \
+        --rotationAxis           "(0 0 1)"              \
+        --rotationAngle          -90                    \
+        --zone                   sideWallC_D_cyclic2Zone
+
+    pyFoamChangeGGIBoundary.py . sideWallD_E_cyclic1    \
+        --shadowPatch            sideWallD_E_cyclic2    \
+        --rotationAxis           "(0 0 1)"              \
+        --rotationAngle          90                     \
+        --zone                   sideWallD_E_cyclic1Zone
+
+    pyFoamChangeGGIBoundary.py . sideWallD_E_cyclic2    \
+        --shadowPatch            sideWallD_E_cyclic1    \
+        --rotationAxis           "(0 0 1)"              \
+        --rotationAngle          -90                    \
+        --zone                   sideWallD_E_cyclic2Zone
+
+    pyFoamChangeGGIBoundary.py . sideWallE_F_cyclic1    \
+        --shadowPatch            sideWallE_F_cyclic2    \
+        --rotationAxis           "(0 0 1)"              \
+        --rotationAngle          90                     \
+        --zone                   sideWallE_F_cyclic1Zone
+
+    pyFoamChangeGGIBoundary.py . sideWallE_F_cyclic2    \
+        --shadowPatch            sideWallE_F_cyclic1    \
+        --rotationAxis           "(0 0 1)"              \
+        --rotationAngle          -90                    \
+        --zone                   sideWallE_F_cyclic2Zone
+
+else
+    echo "pyFoamChangeGGIBoundary.py is missing. Using the file constant/polyMesh/boundary.preconfigured"
+    cp constant/polyMesh/boundary.preconfigured constant/polyMesh/boundary
+fi
 
 echo "$caseName: Creating the starting time directory"
 cp -r 0_orig 0
diff --git a/tutorials/incompressible/simpleFoam/ERCOFTAC_ConicalDiffuser/Case1.1_mixingPlane_sector_AB_60deg/Allrun b/tutorials/incompressible/simpleFoam/ERCOFTAC_ConicalDiffuser/Case1.1_mixingPlane_sector_AB_60deg/Allrun
--- a/tutorials/incompressible/simpleFoam/ERCOFTAC_ConicalDiffuser/Case1.1_mixingPlane_sector_AB_60deg/Allrun
+++ b/tutorials/incompressible/simpleFoam/ERCOFTAC_ConicalDiffuser/Case1.1_mixingPlane_sector_AB_60deg/Allrun
@@ -10,7 +10,7 @@
 export caseName=`basename $PWD`
 
 #We stop this script when we encounter a problem
-trap "exit -1" ERR
+#trap "exit -1" ERR
 
 echo "$caseName: Creating the file blockMeshDict using m4"
 (cd constant/polyMesh; m4 -P blockMeshDict.m4 > blockMeshDict)
@@ -19,7 +19,45 @@ echo "$caseName: Running blockMesh"
 runApplicationAndReportOnError blockMesh
 
 echo "$caseName: Updating the boundary file"
-cp constant/polyMesh/boundary.preconfigured constant/polyMesh/boundary
+# Let's see if pyFoamChangeMixingPlaneBoundary.py is available
+command -v pyFoamChangeMixingPlaneBoundary.py >/dev/null
+if [ $? -eq 0 ];
+then
+    echo "Using pyFoamChangeMixingPlaneBoundary.py"
+    pyFoamChangeMixingPlaneBoundary.py . B_UPSTREAM     \
+        --shadowPatch                    B_DOWNSTREAM   \
+        --assembly                       both           \
+        --orientation                    dirR_spanTheta \
+        --coordinateSystemType           cylindrical    \
+        --coordinateSystemOrigin         "(0 0 0)"      \
+        --coordinateSystemE1             "(1 0 0)"      \
+        --coordinateSystemE3             "(0 0 1)"
+
+    pyFoamChangeMixingPlaneBoundary.py . B_DOWNSTREAM   \
+        --shadowPatch                    B_UPSTREAM     \
+        --assembly                       both           \
+        --orientation                    dirR_spanTheta \
+        --coordinateSystemType           cylindrical    \
+        --coordinateSystemOrigin         "(0 0 0)"      \
+        --coordinateSystemE1             "(1 0 0)"      \
+        --coordinateSystemE3             "(0 0 1)"
+
+    echo "Using pyFoamChangeGGIBoundary.py"
+    pyFoamChangeGGIBoundary.py . sideWallA_BB_cyclic1    \
+        --shadowPatch            sideWallA_BB_cyclic2    \
+        --rotationAxis           "(0 0 1)"               \
+        --rotationAngle          60                      \
+        --zone                   sideWallA_BB_cyclic1Zone
+
+    pyFoamChangeGGIBoundary.py . sideWallA_BB_cyclic2    \
+        --shadowPatch            sideWallA_BB_cyclic1    \
+        --rotationAxis           "(0 0 1)"               \
+        --rotationAngle          -60                     \
+        --zone                   sideWallA_BB_cyclic2Zone
+else
+    echo "pyFoamChangeGGIBoundary.py is missing. Using the file constant/polyMesh/boundary.preconfigured"
+    cp constant/polyMesh/boundary.preconfigured constant/polyMesh/boundary
+fi
 
 echo "$caseName: Creating the starting time directory"
 cp -r 0_orig 0
diff --git a/tutorials/incompressible/simpleFoam/mixingPlaneAxial/Allrun b/tutorials/incompressible/simpleFoam/mixingPlaneAxial/Allrun
--- a/tutorials/incompressible/simpleFoam/mixingPlaneAxial/Allrun
+++ b/tutorials/incompressible/simpleFoam/mixingPlaneAxial/Allrun
@@ -10,7 +10,7 @@
 export caseName=`basename $PWD`
 
 #We stop this script when we encounter a problem
-trap "exit -1" ERR
+#trap "exit -1" ERR
 
 echo "$caseName: Creating the file blockMeshDict using m4"
 (cd constant/polyMesh; m4 -P blockMeshDict.m4 > blockMeshDict)
@@ -19,8 +19,59 @@ echo "$caseName: Running blockMesh"
 runApplicationAndReportOnError blockMesh
 
 echo "$caseName: Updating the boundary file"
-#if not using PyFOAM, use this pre-configured boundary file
-cp constant/polyMesh/boundary.preconfigured constant/polyMesh/boundary
+# Let's see if pyFoamChangeMixingPlaneBoundary.py is available
+command -v pyFoamChangeMixingPlaneBoundary.py >/dev/null
+if [ $? -eq 0 ];
+then
+    echo "Using pyFoamChangeMixingPlaneBoundary.py"
+    pyFoamChangeMixingPlaneBoundary.py . upstreamMixingPlanePatch   \
+	--shadowPatch                    downstreamMixingPlanePatch \
+	--assembly                       both                       \
+	--orientation                    dirZ_spanTheta             \
+	--coordinateSystemType           cylindrical                \
+	--coordinateSystemOrigin         "(0 0 0)"                  \
+	--coordinateSystemE1             "(1 0 0)"                  \
+	--coordinateSystemE3             "(0 0 1)"        
+
+    pyFoamChangeMixingPlaneBoundary.py . downstreamMixingPlanePatch \
+	--shadowPatch                    upstreamMixingPlanePatch   \
+	--assembly                       both                       \
+	--orientation                    dirZ_spanTheta             \
+	--coordinateSystemType           cylindrical                \
+	--coordinateSystemOrigin         "(0 0 0)"                  \
+	--coordinateSystemE1             "(1 0 0)"                  \
+	--coordinateSystemE3             "(0 0 1)"        
+
+
+    echo "Using pyFoamChangeGGIBoundary.py"
+    pyFoamChangeGGIBoundary.py . upstreamPerio1    \
+        --shadowPatch            upstreamPerio2    \
+        --rotationAxis           "(0 0 1)"         \
+        --rotationAngle          36                \
+        --zone                   upstreamPerio1Zone
+
+    pyFoamChangeGGIBoundary.py . upstreamPerio2    \
+        --shadowPatch            upstreamPerio1    \
+        --rotationAxis           "(0 0 1)"         \
+        --rotationAngle          -36               \
+        --zone                   upstreamPerio2Zone
+
+    pyFoamChangeGGIBoundary.py . downstreamPerio1    \
+        --shadowPatch            downstreamPerio2    \
+        --rotationAxis           "(0 0 1)"           \
+        --rotationAngle          90                  \
+        --zone                   downstreamPerio1Zone
+
+    pyFoamChangeGGIBoundary.py . downstreamPerio2    \
+        --shadowPatch            downstreamPerio1    \
+        --rotationAxis           "(0 0 1)"           \
+        --rotationAngle          -90                 \
+        --zone                   downstreamPerio2Zone
+else
+    echo "pyFoamChangeMixingPlaneBoundary.py is missing. Using the file constant/polyMesh/boundary.preconfigured"
+    cp constant/polyMesh/boundary.preconfigured constant/polyMesh/boundary
+fi
+
 
 echo "$caseName: Creating the starting time directory"
 cp -r 0_orig 0
